In [ ]:
'''
Assignment 2: Study of Python Basic Libraries: Numpy

1. Create a 1D array from a Python list 
2. Create a 2D array (matrix)
3. Perform element-wise operations (e.g., add 2 to every element)  
4. Calculate the sum of all element
5. Create a 4x4 empty array and the shape is passed as a tuple (4, 4)  
6. Create a 4x4 array filled with the value 5 
7. Generate an array 10 random numbers sampled from standard normal distribution  
8. Find dot product of two arrays (consider two 2x2 arrays)
9. Sort a NumPy array along rows, columns, as a whole
# by considering 3x3 array  
10. Make a list of 3 numpy arrays and find the mean, median, variance and standard deviation of all the arrays and output them as a list  
11. Create a NumPy array of strings   (example: "[apple banana cherry mango kiwi]") and split them (example out should be: 

[list(['apple', 'banana', 'cherry', 'mango', 'kiwi'])]

'''

In [34]:
import numpy as np 

In [35]:
lst = [1 , 2 , 3 , 4 , 5]
arr = np.array(lst)
print(lst)
print(arr) 


[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [36]:
arr1 = np.array([[1 , 2 , 3] , 
              [4 , 5 , 6] , 
              [7 , 8 , 9]])
print(arr1) 

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [37]:
# adding 2 to arr 
result = arr + 2 
print("result on arr")
print(result)
#adding 2 to arr1
print("result on arr1 ")
result1 = arr1 + 2 
print(result1)

result on arr
[3 4 5 6 7]
result on arr1 
[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [38]:
# sum of all element on arr ;
print(f'Sum of arr : {np.sum(arr)}' )

# sum of all element on arr1 ;
print(f'Sum of arr1 : {np.sum(arr1)}' )

Sum of arr : 15
Sum of arr1 : 45


In [39]:
# 4x4 empty array 
arr2 = np.empty((4 , 4))
print(arr2)
#since its empty it have garbage value 

[[9.91199487e-312 4.54540394e-322 0.00000000e+000 0.00000000e+000]
 [2.22522596e-306 1.16095484e-028 1.52668844e-153 9.13616837e+242]
 [9.29846251e+242 5.28595592e-085 1.92430394e-057 4.07175423e+223]
 [9.15279752e+242 1.46899930e+179 9.08367237e+223 1.16466228e-028]]


In [40]:
# 4x4 array with all val = 5
arr2 = np.full((4 , 4) , 5)
print(arr2)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [41]:
# random number array of size 10 
arr3 = np.random.randn(10)
print(arr3)

[-0.15259184  1.08325657 -0.18026527  0.43953097  0.6953148  -0.19131302
 -0.07361227  1.10005265 -0.52810648  0.11055583]


In [42]:
# dot product of of two 2 x 2 number array
arr4a = np.array([[1 , 2] , 
                 [3 , 4]]) 
arr4b = np.array([[5 , 6] , 
                 [7 , 8]]) 
result2 = np.dot(arr4a , arr4b) 
print(f'dot product of two 2 x 2 array : \n{result2}')

dot product of two 2 x 2 array : 
[[19 22]
 [43 50]]


In [43]:
# sorting an array along row , column and whole 
# using arr1 as original array and making copy of it 
arr5 = np.array([[1 , 12 , 3] , 
              [14 , 15 , 6] , 
              [7 , 18 , 9]])
print(f'Original array : \n{arr5} \n sorted one (whole) : \n{np.sort(arr5 , axis = None)}')
print(f'Original array : \n{arr5} \n sorted one (row) : \n{np.sort(arr5 , axis = 0)}')
print(f'Original array : \n{arr5} \n sorted one (column) : \n{np.sort(arr5 , axis = 1)}')

Original array : 
[[ 1 12  3]
 [14 15  6]
 [ 7 18  9]] 
 sorted one (whole) : 
[ 1  3  6  7  9 12 14 15 18]
Original array : 
[[ 1 12  3]
 [14 15  6]
 [ 7 18  9]] 
 sorted one (row) : 
[[ 1 12  3]
 [ 7 15  6]
 [14 18  9]]
Original array : 
[[ 1 12  3]
 [14 15  6]
 [ 7 18  9]] 
 sorted one (column) : 
[[ 1  3 12]
 [ 6 14 15]
 [ 7  9 18]]


In [46]:
arr6 = [
    np.array([1 , 2 , 4]) , 
    np.array([3 , 9 , 5]) , 
    np.array([8 , 6 , 7])
]
mean_arr = [np.mean(a) for a in arr6] 
median_arr = [np.median(a) for a in arr6] 
varience_arr = [np.var(a) for a in arr6] 
std_dev_arr = [np.std(a) for a in arr6] 
print(f'mean for arr6 is : {mean_arr} \n median for arr6 is {median_arr} \n varience for arr6 is {varience_arr} \n standard deviation for arr6 is {std_dev_arr}')


mean for arr6 is : [2.3333333333333335, 5.666666666666667, 7.0] 
 median for arr6 is [2.0, 5.0, 7.0] 
 varience for arr6 is [1.5555555555555554, 6.222222222222222, 0.6666666666666666] 
 standard deviation for arr6 is [1.247219128924647, 2.494438257849294, 0.816496580927726]


In [48]:
arr7 = np.array(["apple banana cherry mango kiwi"])
result3 = [arr7[0].split()] 
print(result3)

[['apple', 'banana', 'cherry', 'mango', 'kiwi']]


In [ ]:
# end of lab 2 assignment 